services:
  api:
    build:
      context: ./api
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: rebuild
          path: ./api/src

  client:
    profiles: ["client"]
    build:
      context: ./client
      target: build
